version: '3.7'

services: 
    postgres:
        image: 'postgres:12.3'
        volumes: 
            - 'postgres:/var/lib/postgresql/data'
        environment: 
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres

    redis:
        image: 'redis:6.0.3-alpine'
        command: redis-server
        ports: 
            - '6379:6379'
        volumes: 
            - 'redis:/var/lib/redis/data'

    jobs:
        depends_on: 
            - postgres
            - redis
            - website
        build: .
        command: bash start_jobs
        volumes: 
            - '.:/nosso_amigo_secreto'

    website:
        depends_on: 
            - postgres
            - redis
        build: .
        command: bash start
        ports: 
             - '3000:3000'
        volumes: 
            - '.:/nosso_amigo_secreto'
            - 'box:/box'
        environment: 
            - BUNDLE_PATH=/box 
            - DB_HOST=postgres
            - DB_USER=postgres
            - DB_PASS=postgres

    box:
        image: busybox
        volumes: 
            - box:/box

volumes: 
    redis:
    postgres:
    box: